<li class="<?php echo $this->class ?>">
    <?php echo $this->formLabel($this->element->getName(),
                         $this->element->getLabel()) ?>

    <?php echo $this->element->getValue() ?>

    <input style="margin-left: 10px;" type="file" name="<?php echo $this->element->getName(); // necessary for array notation ?>" value="<?php echo $this->element->getValue()?>" <?php echo $this->element->getAttribs() ?> />

    <?php if ($messages = $this->element->getMessages()): echo $this->formErrors($this->element->getMessages()); endif ?>

    <div class="help"><?php echo $this->element->getDescription() ?></div>
</li>